name: Auto-generate docs index for KiCad-Hierarchical-Designs

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**/index.md"
      - ".github/workflows/generate-and-deploy.yml"

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Generate all docs/index.md
        run: python scripts/generate_docs_index.py

      - name: Commit & push changes
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "🔁 Auto-generate docs index"
            git push origin HEAD:main
          else
            echo "✅ Indexes up to date"
          fi
